name: Build ZMK firmware
on:
  push:
    paths:
      - "build.yaml"
      - ".github/workflows/build-firmware.yml"  
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      archive_name: booxie-daisy
