name: Build ZMK firmware
on:
  push:
    paths:
      - "**.yml"
      - "**.yaml"
      - "boards/**"
  pull_request:
  workflow_dispatch:

jobs:
  build:
    uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    with:
      archive_name: booxiedaisy
